import {
  View, Text, ScrollView, TouchableOpacity,
  StyleSheet,
} from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { COLORS, FONT, RADIUS } from '../src/lib/theme';

export default function PrivacyPolicyScreen() {
  return (
    <SafeAreaView style={styles.safe}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => router.back()} style={styles.backBtn}>
          <Ionicons name="arrow-back" size={22} color={COLORS.textPrimary} />
        </TouchableOpacity>
        <Text style={styles.headerTitle}>Privacy Policy</Text>
        <View style={{ width: 36 }} />
      </View>

      <ScrollView style={styles.scroll}>
        <View style={styles.card}>
          <Text style={styles.updated}>Last updated: July 2026</Text>

          <Text style={styles.paragraph}>
            PensionSim is an academic Operations Research case-study project, not a
            commercial product. This policy explains what data the app collects and how
            it is used.
          </Text>

          <Text style={styles.sectionTitle}>What we collect</Text>
          <Text style={styles.paragraph}>
            When you create an account, we collect your email address and, optionally,
            your display name. When you build a retirement plan, we store the simulation
            inputs you provide — such as your starting age, retirement age, contribution
            amounts, and chosen interest rate assumptions — along with the results
            generated by the simulation engine.
          </Text>

          <Text style={styles.sectionTitle}>How your data is stored</Text>
          <Text style={styles.paragraph}>
            All data is stored in Supabase, a hosted PostgreSQL platform used as the
            backend for this app. Access is protected by authentication and row-level
            security so that you can only view and edit your own saved plans.
          </Text>

          <Text style={styles.sectionTitle}>How your data is used</Text>
          <Text style={styles.paragraph}>
            Your data is used solely to provide the app's functionality — saving and
            displaying your simulations, comparing plans, and personalizing your
            experience. It is not sold, rented, or shared with third parties, and it is
            not used for advertising.
          </Text>

          <Text style={styles.sectionTitle}>Academic context</Text>
          <Text style={styles.paragraph}>
            This app was built as part of an academic Operations Research module. Data
            collected may be reviewed by the project author for the purposes of grading,
            debugging, or improving the app, but is not published or distributed
            externally.
          </Text>

          <Text style={styles.sectionTitle}>Contact</Text>
          <Text style={styles.paragraph}>
            If you have questions about this policy or your data, please contact the
            app developer directly.
          </Text>
        </View>

        <View style={{ height: 40 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: COLORS.background },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingVertical: 14,
    backgroundColor: COLORS.surface,
    borderBottomWidth: 1, borderBottomColor: COLORS.border,
  },
  backBtn: { width: 36, height: 36, justifyContent: 'center' },
  headerTitle: { fontSize: FONT.lg, fontWeight: '700', color: COLORS.textPrimary },
  scroll: { flex: 1, padding: 16 },
  card: {
    backgroundColor: COLORS.surface,
    borderRadius: RADIUS.md, padding: 16,
    borderWidth: 1, borderColor: COLORS.border,
  },
  updated: { fontSize: FONT.sm, color: COLORS.textMuted, marginBottom: 16 },
  sectionTitle: {
    fontSize: FONT.base, fontWeight: '700', color: COLORS.textPrimary,
    marginTop: 16, marginBottom: 6,
  },
  paragraph: { fontSize: FONT.md, color: COLORS.textSecondary, lineHeight: 21 },
});
